-- Ensure the messages table exists with the correct schema
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    message TEXT,
    group_name TEXT NOT NULL,
    image_url TEXT,
    video_url TEXT,
    audio_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_messages_group_name ON messages(group_name);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
